FROM node:alpine

ENV REACT_APP_RUNTIME=Development

ENV REACT_APP_SERVER_URL=https://proxy.time.silverse.mx
ENV REACT_APP_NAME="Silvertime Login (Dev)"
ENV REACT_APP_JWT_KEY=silvertime-dev-jwt
ENV REACT_APP_LOGIN=http://login.localhost.com
ENV REACT_APP_ADMIN=http://admin.localhost.com
ENV REACT_APP_OVERVIEW=http://overview.localhost.com

ENV NODE_OPTIONS=--openssl-legacy-provider

WORKDIR "/home/silvertime"
COPY ./package.json ./
CMD ["npm", "run", "start"]
